export const mockUser = {
  uid: 'user_001',
  name: 'Rahim Ahmed',
  namebn: 'রাহিম আহমেদ',
  phone: '+880 1711-234567',
  email: 'rahim@email.com',
  wallet_balance: 1250.5,
  nid_status: 'verified' as const,
  avatar_url: null,
  member_since: '2024-01-15',
};

export const mockVehicles = [
  {
    id: 'vh_001',
    plate: 'DHAKA METRO GA 11-1111',
    platebn: 'ঢাকা মেট্রো গ ১১-১১১১',
    type: 'car' as const,
    owner: 'Rahim Ahmed',
    brtc_status: 'verified' as const,
    color: '#1C3E72',
    active: true,
    model: 'Toyota Allion',
    year: 2022,
  },
  {
    id: 'vh_002',
    plate: 'DHAKA METRO CHA 22-2222',
    platebn: 'ঢাকা মেট্রো চ ২২-২২২২',
    type: 'motorcycle' as const,
    owner: 'Rahim Ahmed',
    brtc_status: 'pending' as const,
    color: '#C0392B',
    active: false,
    model: 'Yamaha FZ',
    year: 2023,
  },
  {
    id: 'vh_003',
    plate: 'CHITTAGONG METRO KA 33-3333',
    platebn: 'চট্টগ্রাম মেট্রো ক ৩৩-৩৩৩৩',
    type: 'truck' as const,
    owner: 'Rahim Ahmed',
    brtc_status: 'verified' as const,
    color: '#27AE60',
    active: false,
    model: 'Tata 407',
    year: 2021,
  },
];

export const mockTransactions = [
  {
    id: 'tx_001',
    type: 'toll' as const,
    gate: 'Jamuna Bridge',
    gatebn: 'যমুনা সেতু',
    amount: -60,
    vehicle_id: 'vh_001',
    gate_id: 'gate_001',
    timestamp: '2026-04-18T10:30:00',
    status: 'success' as const,
    receipt_url: '#',
    road: 'N4 Highway',
  },
  {
    id: 'tx_002',
    type: 'deposit' as const,
    gate: 'Add Money via bKash',
    gatebn: 'বিকাশ দিয়ে যোগ করা',
    amount: 500,
    vehicle_id: null,
    gate_id: null,
    timestamp: '2026-04-18T09:15:00',
    status: 'success' as const,
    receipt_url: '#',
    road: null,
  },
  {
    id: 'tx_003',
    type: 'toll' as const,
    gate: 'Meghna Bridge',
    gatebn: 'মেঘনা সেতু',
    amount: -40,
    vehicle_id: 'vh_001',
    gate_id: 'gate_002',
    timestamp: '2026-04-17T14:20:00',
    status: 'success' as const,
    receipt_url: '#',
    road: 'N2 Highway',
  },
  {
    id: 'tx_004',
    type: 'toll' as const,
    gate: 'Padma Bridge',
    gatebn: 'পদ্মা সেতু',
    amount: -200,
    vehicle_id: 'vh_001',
    gate_id: 'gate_003',
    timestamp: '2026-04-16T08:45:00',
    status: 'success' as const,
    receipt_url: '#',
    road: 'N8 Highway',
  },
  {
    id: 'tx_005',
    type: 'refund' as const,
    gate: 'Refund - Overcharge',
    gatebn: 'অতিরিক্ত চার্জ ফেরত',
    amount: 40,
    vehicle_id: 'vh_001',
    gate_id: 'gate_002',
    timestamp: '2026-04-15T16:00:00',
    status: 'success' as const,
    receipt_url: '#',
    road: null,
  },
  {
    id: 'tx_006',
    type: 'deposit' as const,
    gate: 'Add Money via Nagad',
    gatebn: 'নগদ দিয়ে যোগ করা',
    amount: 1000,
    vehicle_id: null,
    gate_id: null,
    timestamp: '2026-04-14T11:30:00',
    status: 'success' as const,
    receipt_url: '#',
    road: null,
  },
  {
    id: 'tx_007',
    type: 'toll' as const,
    gate: 'Kanchpur Bridge',
    gatebn: 'কাঞ্চপুর সেতু',
    amount: -30,
    vehicle_id: 'vh_001',
    gate_id: 'gate_004',
    timestamp: '2026-04-13T07:15:00',
    status: 'success' as const,
    receipt_url: '#',
    road: 'N2 Highway',
  },
  {
    id: 'tx_008',
    type: 'toll' as const,
    gate: 'Jamuna Bridge',
    gatebn: 'যমুনা সেতু',
    amount: -60,
    vehicle_id: 'vh_001',
    gate_id: 'gate_001',
    timestamp: '2026-04-12T16:00:00',
    status: 'success' as const,
    receipt_url: '#',
    road: 'N4 Highway',
  },
];

export const mockTollGates = [
  {
    id: 'gate_001',
    name: 'Jamuna Bridge',
    namebn: 'যমুনা সেতু',
    road_name: 'N4 Highway',
    status: 'active' as const,
    distance: '2.3 km',
    toll_rates: { motorcycle: 30, car: 60, truck: 200, bus: 150 },
    queue: 3,
  },
  {
    id: 'gate_002',
    name: 'Meghna Bridge',
    namebn: 'মেঘনা সেতু',
    road_name: 'N2 Highway',
    status: 'active' as const,
    distance: '5.1 km',
    toll_rates: { motorcycle: 20, car: 40, truck: 150, bus: 100 },
    queue: 1,
  },
  {
    id: 'gate_003',
    name: 'Padma Bridge',
    namebn: 'পদ্মা সেতু',
    road_name: 'N8 Highway',
    status: 'active' as const,
    distance: '12.7 km',
    toll_rates: { motorcycle: 100, car: 200, truck: 600, bus: 400 },
    queue: 7,
  },
  {
    id: 'gate_004',
    name: 'Kanchpur Bridge',
    namebn: 'কাঞ্চপুর সেতু',
    road_name: 'N2 Highway',
    status: 'maintenance' as const,
    distance: '18.4 km',
    toll_rates: { motorcycle: 15, car: 30, truck: 100, bus: 70 },
    queue: 0,
  },
];

export const mockPasses = [
  {
    id: 'pass_001',
    type: 'monthly' as const,
    price: 500,
    duration: '30 days',
    vehicle_limit: 1,
    active: true,
    purchased: '2026-04-01',
    expires: '2026-05-01',
    days_left: 13,
    benefits: ['Unlimited toll passes', 'FastPass lane access', '10% discount'],
  },
];

export const mockChartData = [
  { day: '1', amount: 60 },
  { day: '3', amount: 0 },
  { day: '5', amount: 200 },
  { day: '7', amount: 0 },
  { day: '9', amount: 40 },
  { day: '11', amount: 0 },
  { day: '13', amount: 30 },
  { day: '15', amount: 60 },
  { day: '17', amount: 0 },
  { day: '18', amount: 260 },
];

export const mockAdminGates = [
  {
    id: 'gate_001',
    name: 'যমুনা সেতু - Lane 1',
    status: 'open' as const,
    vehicles_today: 1247,
    revenue_today: 74820,
    last_vehicle: '2 sec ago',
    operator: 'Karim Hossain',
  },
  {
    id: 'gate_002',
    name: 'যমুনা সেতু - Lane 2',
    status: 'open' as const,
    vehicles_today: 983,
    revenue_today: 58980,
    last_vehicle: '5 sec ago',
    operator: 'Rafi Islam',
  },
  {
    id: 'gate_003',
    name: 'মেঘনা সেতু - Lane 1',
    status: 'maintenance' as const,
    vehicles_today: 412,
    revenue_today: 16480,
    last_vehicle: '4 min ago',
    operator: 'Sumon Das',
  },
];

export const mockRevenueData = [
  { day: 'Mon', revenue: 128400 },
  { day: 'Tue', revenue: 142800 },
  { day: 'Wed', revenue: 118600 },
  { day: 'Thu', revenue: 156200 },
  { day: 'Fri', revenue: 189400 },
  { day: 'Sat', revenue: 201800 },
  { day: 'Sun', revenue: 174600 },
];

export const mockNotifications = [
  {
    id: 'n_001',
    type: 'payment' as const,
    title: 'Toll Paid Successfully',
    titlebn: 'টোল পেমেন্ট সফল',
    body: 'যমুনা সেতু — ৳60 deducted from your wallet',
    timestamp: '2026-04-18T10:30:00',
    read: false,
  },
  {
    id: 'n_002',
    type: 'deposit' as const,
    title: 'Money Added',
    titlebn: 'টাকা যোগ হয়েছে',
    body: '৳500 added via bKash successfully',
    timestamp: '2026-04-18T09:15:00',
    read: false,
  },
  {
    id: 'n_003',
    type: 'warning' as const,
    title: 'Upcoming Toll',
    titlebn: 'আসছে টোল গেট',
    body: 'মেঘনা সেতু is 5.1 km ahead on your current route',
    timestamp: '2026-04-17T14:00:00',
    read: true,
  },
  {
    id: 'n_004',
    type: 'system' as const,
    title: 'Vehicle Verified',
    titlebn: 'গাড়ি যাচাই হয়েছে',
    body: 'DHAKA METRO GA 11-1111 has been verified via BRTC',
    timestamp: '2026-04-16T10:00:00',
    read: true,
  },
  {
    id: 'n_005',
    type: 'promo' as const,
    title: 'Monthly Pass Offer',
    titlebn: 'মাসিক পাস অফার',
    body: 'Save ৳100 on monthly pass this Eid season!',
    timestamp: '2026-04-15T08:00:00',
    read: true,
  },
];
