// lib/domain/entities/toll_transaction_entity.dart
import 'package:freezed_annotation/freezed_annotation.dart';
part 'toll_transaction_entity.freezed.dart';
part 'toll_transaction_entity.g.dart';

@freezed
abstract class TollTransactionEntity with _$TollTransactionEntity {
  const factory TollTransactionEntity({
    required String id,
    required String userUid,
    required String vehicleReg,
    required String bridgeName,
    required double amount,
    required String status, // success, failed, pending
    required DateTime timestamp,
  }) = _TollTransactionEntity;

  factory TollTransactionEntity.fromJson(Map<String, dynamic> json) =>
      _$TollTransactionEntityFromJson(json);

  /// Convert entity to JSON. The real implementation is generated by
  /// `json_serializable` / `freezed` in the `*.g.dart` part file.
  Map<String, dynamic> toJson();
}
