// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-ni41vjbvr_6DRf3RAT4pDhZfCYBLcLU',
    appId: '1:942408037240:web:81bce2e12b6109dfc9ce8d',
    messagingSenderId: '942408037240',
    projectId: 'tollswift-bd-6194f',
    authDomain: 'tollswift-bd-6194f.firebaseapp.com',
    storageBucket: 'tollswift-bd-6194f.firebasestorage.app',
    measurementId: 'G-MPRQ58JG9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Lv4v2tnSWqyvO6MQO2NhAZoG5P8l2ls',
    appId: '1:942408037240:android:4846c8a60d65a666c9ce8d',
    messagingSenderId: '942408037240',
    projectId: 'tollswift-bd-6194f',
    storageBucket: 'tollswift-bd-6194f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXaLKxNHsVLE4QUeG87X4kpUhnHWrj_Oc',
    appId: '1:942408037240:ios:4b91896bc2c408dfc9ce8d',
    messagingSenderId: '942408037240',
    projectId: 'tollswift-bd-6194f',
    storageBucket: 'tollswift-bd-6194f.firebasestorage.app',
    iosClientId: '942408037240-fon6gtbesa10an8o8j387l1sktq9hol5.apps.googleusercontent.com',
    iosBundleId: 'com.example.tollswiftBd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXaLKxNHsVLE4QUeG87X4kpUhnHWrj_Oc',
    appId: '1:942408037240:ios:4b91896bc2c408dfc9ce8d',
    messagingSenderId: '942408037240',
    projectId: 'tollswift-bd-6194f',
    storageBucket: 'tollswift-bd-6194f.firebasestorage.app',
    iosClientId: '942408037240-fon6gtbesa10an8o8j387l1sktq9hol5.apps.googleusercontent.com',
    iosBundleId: 'com.example.tollswiftBd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-ni41vjbvr_6DRf3RAT4pDhZfCYBLcLU',
    appId: '1:942408037240:web:f69cd265138a12b5c9ce8d',
    messagingSenderId: '942408037240',
    projectId: 'tollswift-bd-6194f',
    authDomain: 'tollswift-bd-6194f.firebaseapp.com',
    storageBucket: 'tollswift-bd-6194f.firebasestorage.app',
    measurementId: 'G-VW8PRBGC5H',
  );
}
