// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSAo3i8gWgdNIb9jaGP21l3kOB5UAxG60',
    appId: '1:125386761920:web:1506c9983a1279b284af25',
    messagingSenderId: '125386761920',
    projectId: 'tollbd',
    authDomain: 'tollbd.firebaseapp.com',
    storageBucket: 'tollbd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQz-zp0StIDo1hMPj1780pHfbJuj2G8NU',
    appId: '1:125386761920:android:d8e11b34699a814484af25',
    messagingSenderId: '125386761920',
    projectId: 'tollbd',
    storageBucket: 'tollbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwtVFyY3Ld3AC6oQtyJiWOFdVBGvXvE38',
    appId: '1:125386761920:ios:4c0f5740b802a3f884af25',
    messagingSenderId: '125386761920',
    projectId: 'tollbd',
    storageBucket: 'tollbd.firebasestorage.app',
    iosBundleId: 'com.example.tollbd',
  );
}
