class AppStrings {
  static String get(
    String key,
    String language, {
    Map<String, String> args = const {},
  }) {
    final raw = language == 'bn' ? (_bn[key] ?? key) : (_en[key] ?? key);
    var value = raw;
    for (final entry in args.entries) {
      value = value.replaceAll('{${entry.key}}', entry.value);
    }
    return value;
  }

  static const Map<String, String> _bn = {
    'app_name': 'TollBD',
    'tagline': 'স্মার্ট টোল, সহজ যাত্রা',
    'powered_by': 'Powered by Bangladesh Road Transport Authority',
    'continue': 'চালিয়ে যান',
    'bengali': 'বাংলা',
    'english': 'English',
    'enter_number': 'আপনার নম্বর দিন',
    'otp_subtitle': 'আমরা আপনাকে একটি OTP পাঠাবো',
    'send_otp': 'OTP পাঠান',
    'terms_text':
        'এগিয়ে যাওয়ার মাধ্যমে আপনি আমাদের Terms of Service মেনে নিচ্ছেন',
    'verify_otp': 'OTP যাচাই করুন',
    'otp_sent_to': '6-digit code sent to your number',
    'resend_otp_in': 'Resend OTP in {time}',
    'resend_otp': 'Resend OTP',
    'verify': 'যাচাই করুন',
    'wrong_otp': 'ভুল OTP',
    'profile_setup': 'প্রোফাইল সেটআপ',
    'your_name': 'আপনার নাম লিখুন',
    'your_name_en': 'Name (English, optional)',
    'next': 'পরবর্তী',
    'biometric_title': 'দ্রুত লগইনের জন্য Biometric চালু করুন',
    'biometric_subtitle': 'আপনার আঙুলের ছাপ বা Face ID দিয়ে নিরাপদে লগইন করুন',
    'biometric_enable': 'চালু করুন',
    'not_now': 'এখন না',
    'unlock_title': 'Biometric দিয়ে অ্যাপ আনলক করুন',
    'unlock_subtitle': 'আপনার আঙুলের ছাপ বা Face ID দিয়ে চালিয়ে যান',
    'unlock_now': 'এখন আনলক করুন',
    'hello': 'হ্যালো',
    'good_morning': 'সুপ্রভাত',
    'good_afternoon': 'শুভ অপরাহ্ন',
    'good_evening': 'শুভ সন্ধ্যা',
    'your_balance': 'আপনার ব্যালেন্স',
    'add_money': 'টাকা যোগ করুন',
    'pay_toll': 'টোল দিন',
    'transaction_history': 'লেনদেনের ইতিহাস',
    'low_balance_warning': 'আপনার ব্যালেন্স কম',
    'deposit_success': 'ওয়ালেটে টাকা যোগ হয়েছে',
    'select_payment_method': 'পেমেন্ট পদ্ধতি বেছে নিন',
    'recent_transactions': 'সাম্প্রতিক লেনদেন',
    'see_all': 'সব দেখুন',
    'no_transactions': 'এখনো কোনো লেনদেন নেই',
    'wallet': 'ওয়ালেট',
    'history': 'ইতিহাস',
    'vehicles': 'গাড়ি',
    'profile': 'প্রোফাইল',
    'notifications': 'নোটিফিকেশন',
    'this_week_spending': 'এই সপ্তাহে ব্যয়',
    'all': 'সব',
    'deposit': 'ডিপোজিট',
    'refund': 'রিফান্ড',
    'amount': 'পরিমাণ',
    'minimum_50': 'সর্বনিম্ন ৳50',
    'maximum_50000': 'সর্বোচ্চ ৳50,000',
    'secure_payment': 'SSLCommerz দ্বারা নিরাপদ পেমেন্ট 🔒',
    'pay_amount': '৳{amount} পরিশোধ করুন',
    'safe_payment': 'নিরাপদ পেমেন্ট 🔒',
    'payment_failed': 'পেমেন্ট ব্যর্থ হয়েছে',
    'today': 'আজ',
    'settings': 'সেটিংস',
    'language': 'ভাষা',
    'biometric': 'Biometric',
    'logout': 'লগআউট',
    'coming_soon': 'শীঘ্রই আসছে',
    'active_vehicle': 'সক্রিয় গাড়ি',
    'add_vehicle': 'গাড়ি যোগ করুন',
  };

  static const Map<String, String> _en = {
    'app_name': 'TollBD',
    'tagline': 'Smart Toll, Easy Journey',
    'powered_by': 'Powered by Bangladesh Road Transport Authority',
    'continue': 'Continue',
    'bengali': 'বাংলা',
    'english': 'English',
    'enter_number': 'Enter your number',
    'otp_subtitle': 'We will send you an OTP',
    'send_otp': 'Send OTP',
    'terms_text': 'By continuing you agree to our Terms of Service',
    'verify_otp': 'Verify OTP',
    'otp_sent_to': '6-digit code sent to your number',
    'resend_otp_in': 'Resend OTP in {time}',
    'resend_otp': 'Resend OTP',
    'verify': 'Verify',
    'wrong_otp': 'Wrong OTP',
    'profile_setup': 'Profile Setup',
    'your_name': 'Enter your name',
    'your_name_en': 'Name (English, optional)',
    'next': 'Next',
    'biometric_title': 'Enable biometric for quick login',
    'biometric_subtitle': 'Use your fingerprint or Face ID to login securely',
    'biometric_enable': 'Enable',
    'not_now': 'Not now',
    'unlock_title': 'Unlock with biometrics',
    'unlock_subtitle': 'Use your fingerprint or Face ID to continue',
    'unlock_now': 'Unlock now',
    'hello': 'Hello',
    'good_morning': 'Good morning',
    'good_afternoon': 'Good afternoon',
    'good_evening': 'Good evening',
    'your_balance': 'Your Balance',
    'add_money': 'Add Money',
    'pay_toll': 'Pay Toll',
    'transaction_history': 'Transaction History',
    'low_balance_warning': 'Low balance',
    'deposit_success': 'Money added to wallet',
    'select_payment_method': 'Select payment method',
    'recent_transactions': 'Recent Transactions',
    'see_all': 'See all',
    'no_transactions': 'No transactions yet',
    'wallet': 'Wallet',
    'history': 'History',
    'vehicles': 'Vehicles',
    'profile': 'Profile',
    'notifications': 'Notifications',
    'this_week_spending': 'This Week Spending',
    'all': 'All',
    'deposit': 'Deposit',
    'refund': 'Refund',
    'amount': 'Amount',
    'minimum_50': 'Minimum ৳50',
    'maximum_50000': 'Maximum ৳50,000',
    'secure_payment': 'Secure payment by SSLCommerz 🔒',
    'pay_amount': 'Pay ৳{amount}',
    'safe_payment': 'Secure Payment 🔒',
    'payment_failed': 'Payment failed',
    'today': 'Today',
    'settings': 'Settings',
    'language': 'Language',
    'biometric': 'Biometric',
    'logout': 'Logout',
    'coming_soon': 'Coming soon',
    'active_vehicle': 'Active Vehicle',
    'add_vehicle': 'Add Vehicle',
  };
}
